In [1]:
import pandas as pd

df = pd.read_csv('/content/IOT-temp 2.csv')

df=df.drop(columns = ['id', 'room_id/id', 'noted_date'])
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
#df = imputer.fit_transform(df)

from sklearn.preprocessing import LabelEncoder
le1= LabelEncoder()


df['out/in']= le1.fit_transform(df['out/in'])

'''
df=df.dropna()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le1 = LabelEncoder()
le2 = LabelEncoder()
'''


#df['icon']= le.fit_transform(df['icon'])

y = df['out/in'].values
df=df.drop(columns = ['out/in'])
X = df.values


In [ ]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
df.shape


(594, 19)

In [ ]:
from collections import Counter
Counter(y)

Counter({0: 20345, 1: 77261})

In [2]:

y=y.reshape(-1, 1)


import numpy as np
X=np.concatenate((X[1:], y[0:-1]), axis=1)

In [1]:
pip install keras-self-attention

  Created wheel for keras-self-attention: filename=keras_self_attention-0.51.0-py3-none-any.whl size=18912 sha256=ce72735f57a4e2d8e301cf849c83355d2600a165783e8958016f3bb1a456bb57
  Stored in directory: /root/.cache/pip/wheels/95/b1/a8/5ee00cc137940b2f6fa198212e8f45d813d0e0d9c3a04035a3
Successfully built keras-self-attention


In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X= sc.fit_transform(X)

In [2]:
pip install pyrcn

     |████████████████████████████████| 81 kB 8.8 MB/s 


In [10]:
from sklearn.model_selection import train_test_split
x_train1, x_test1, y_train1, y_test1 = train_test_split(X, y[1:], test_size=0.2, shuffle=False, random_state=42)


In [ ]:
x_train1.shape

(78084, 2)

In [11]:
from pyrcn.base.blocks import InputToNode
from sklearn . datasets import make_blobs
# Generate a toy dataset

In [12]:
input_to_node = InputToNode (20, input_activation='relu',input_scaling =1.0 )


x_train= input_to_node.fit_transform (x_train1)
x_test= input_to_node.transform (x_test1)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:77: FutureWarning: Pass hidden_layer_size=20 as keyword args. From version 1.1 (renaming of 0.26) passing these as positional arguments will result in an error
  FutureWarning,


In [13]:
from pyrcn.base.blocks import NodeToNode
node_to_node = NodeToNode (20, reservoir_activation='relu', spectral_radius =0.99 , leakage =0.5,bidirectional = False )
x_train=node_to_node . fit_transform(x_train)
x_test= node_to_node.transform (x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:77: FutureWarning: Pass hidden_layer_size=20 as keyword args. From version 1.1 (renaming of 0.26) passing these as positional arguments will result in an error
  FutureWarning,


In [ ]:
x_test[0]

array([ 0.        , 22.00681312, 10.25975643,  5.15342963,  0.        ,
        0.        ,  0.        , 16.85608116])

In [ ]:
x_train[-1]

array([ 0.        , 32.89883769,  8.44760075,  0.        ,  6.02993687,
        0.        ,  0.        ,  8.98919012])

In [ ]:
x_test[0:5]

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        9.39921364e-01, 0.00000000e+00, 3.31548435e-02, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.26567590e-01, 0.00000000e+00,
        1.08160130e+00, 0.00000000e+00, 6.63096869e-03, 6.24059763e-02],
       [0.00000000e+00, 0.00000000e+00, 2.49592404e-01, 0.00000000e+00,
        1.30757630e+00, 0.00000000e+00, 1.32619374e-03, 1.24811953e-02],
       [0.00000000e+00, 0.00000000e+00, 2.96601895e-01, 0.00000000e+00,
        1.28755986e+00, 0.00000000e+00, 2.65238748e-04, 2.49623905e-03],
       [0.00000000e+00, 0.00000000e+00, 2.87851835e-01, 0.00000000e+00,
        1.40041279e+00, 0.00000000e+00, 5.30477495e-05, 4.99247810e-04]])

In [ ]:
x_test[0:10]

array([[5.59295759e-307, 0.00000000e+000, 3.17049322e-001,
        0.00000000e+000, 1.23868465e+000, 2.29709269e-005,
        2.85245730e-004, 8.14299262e-005],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 9.39921364e-001, 0.00000000e+000,
        3.31548435e-002, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.26567590e-001,
        0.00000000e+000, 1.08160130e+000, 0.00000000e+000,
        6.63096869e-003, 6.24059763e-002],
       [0.00000000e+000, 0.00000000e+000, 2.49592404e-001,
        0.00000000e+000, 1.30757630e+000, 0.00000000e+000,
        1.32619374e-003, 1.24811953e-002],
       [0.00000000e+000, 0.00000000e+000, 2.96601895e-001,
        0.00000000e+000, 1.28755986e+000, 0.00000000e+000,
        2.65238748e-004, 2.49623905e-003],
       [0.00000000e+000, 0.00000000e+000, 2.87851835e-001,
        0.00000000e+000, 1.40041279e+000, 0.00000000e+000,
        5.30477495e-005, 4.99247810e-004],
       [0.00000000e+000, 0.0000000

In [14]:
a=x_test[0]
for i in range(1, len(x_test)):
    b=x_test[i].copy()

    x_test[i]=a
    a=b.copy()



In [15]:
x_test[0]=x_train[-1]
x_train1=x_train1[1:]
y_train1=y_train1[1:]

x_train=x_train[:-1]




In [16]:
x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

x_train1 = x_train1.reshape((x_train1.shape[0], x_train1.shape[1], 1))
x_test1 = x_test1.reshape((x_test1.shape[0], x_test1.shape[1], 1))

In [17]:
from tensorflow import keras
from tensorflow.keras import layers

In [18]:
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    # Normalization and Attention
    x = layers.LayerNormalization(epsilon=1e-6)(inputs)
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(x, x)
    x = layers.Dropout(dropout)(x)
    res = x + inputs

    # Feed Forward Part
    x = layers.LayerNormalization(epsilon=1e-6)(res)
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(x)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    return x + res

In [19]:
from keras_self_attention import SeqSelfAttention
def build_model(
    input_shapey,
    input_shapez,
    head_size,
    num_heads,
    ff_dim,
    num_transformer_blocks,
    mlp_units,
    dropout=0,
    mlp_dropout=0,
):
    inputsy = keras.Input(shape=input_shapey)
    inputsz = keras.Input(shape=input_shapez)
    y = inputsy
    z= inputsz

    #z=layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(z)

    #y=layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(y)

    z=SeqSelfAttention()(z)
    z=layers.Flatten()(z)
    
    z=layers.Dense(10, activation="tanh")(z)
    z=layers.Dense(5, activation="tanh")(z)
    z= layers.Reshape((-1,1))(z)



    #y=SeqSelfAttention()(y)



    x=layers.Concatenate(axis=1)([y, z])
    #x=layers.Add()([inputsy, inputsz])

    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.GlobalAveragePooling1D(data_format="channels_first")(x)
    for dim in mlp_units:
        x = layers.Dense(dim, activation="relu")(x)
        x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(2, activation="softmax")(x)
    #outputs = layers.Dense(1)(x)
    return keras.Model([inputsy,inputsz], outputs)

In [25]:
input_shapey = x_train1.shape[1:]
input_shapez = x_train.shape[1:]

model = build_model(
    input_shapey,
    input_shapez,
    head_size=5,
    num_heads=2,
    ff_dim=1,
    num_transformer_blocks=10,
    mlp_units=[64],
    mlp_dropout=0.4,
    dropout=0.25,
)
'''
model.compile(
    loss="mean_absolute_error",
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    metrics=["mean_absolute_error"],
)
'''
model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    metrics=["sparse_categorical_accuracy"],
)

model.summary()





Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_6 (InputLayer)           [(None, 20, 1)]      0           []                               
                                                                                                  
 seq_self_attention_2 (SeqSelfA  (None, 20, 1)       129         ['input_6[0][0]']                
 ttention)                                                                                        
                                                                                                  
 flatten_2 (Flatten)            (None, 20)           0           ['seq_self_attention_2[0][0]']   
                                                                                                  
 dense_8 (Dense)                (None, 10)           210         ['flatten_2[0][0]']        

In [ ]:


callbacks = [keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)]

history=model.fit(
    [x_train1,x_train],
    y_train1,
    validation_data=([x_test1, x_test], y_test1),
    epochs=100,
    batch_size=128,
    callbacks=callbacks,
)

Epoch 1/100
611/611 [==============================] - 23s 31ms/step - loss: 0.2080 - sparse_categorical_accuracy: 0.9132 - val_loss: 0.5023 - val_sparse_categorical_accuracy: 0.7615
Epoch 2/100
611/611 [==============================] - 18s 30ms/step - loss: 0.1446 - sparse_categorical_accuracy: 0.9361 - val_loss: 0.4753 - val_sparse_categorical_accuracy: 0.7580
Epoch 3/100
611/611 [==============================] - 18s 30ms/step - loss: 0.1362 - sparse_categorical_accuracy: 0.9374 - val_loss: 0.4597 - val_sparse_categorical_accuracy: 0.7555
Epoch 4/100
611/611 [==============================] - 18s 30ms/step - loss: 0.1325 - sparse_categorical_accuracy: 0.9381 - val_loss: 0.4605 - val_sparse_categorical_accuracy: 0.7666
Epoch 5/100
611/611 [==============================] - 18s 30ms/step - loss: 0.1297 - sparse_categorical_accuracy: 0.9392 - val_loss: 0.4792 - val_sparse_categorical_accuracy: 0.7530
Epoch 6/100
611/611 [==============================] - 18s 30ms/step - loss: 0.1292 -

In [ ]:
#testing prediction

#testing prediction
ypred1=model.predict([x_test1, x_test])

ypred=[]
#testing prediction
for i in ypred1:
    if i[0]>i[1]:
        ypred.append(0)
    else:
        ypred.append(1)
from sklearn.metrics import accuracy_score, f1_score,  jaccard_score, roc_auc_score, precision_score, recall_score
print(accuracy_score(ypred, y_test1))



print('f1_score', f1_score(ypred, y_test1))



print('jaccard_score', jaccard_score(ypred, y_test1))
print('roc_auc_score', roc_auc_score(ypred, y_test1))
print('precision_score', precision_score(ypred, y_test1))

print('recall_score', recall_score(ypred, y_test1))


0.8023666820347318
f1_score 0.8432599333712523
jaccard_score 0.7289969092441697
roc_auc_score 0.7947379758707105
precision_score 0.8672906568611065
recall_score 0.8205249841872233


In [ ]:
#training prediction
xpred1=model.predict([x_train1, x_train])
xpred=[]

for i in xpred1:
    if i[0]>i[1]:
        xpred.append(0)
    else:
        xpred.append(1)
from sklearn.metrics import accuracy_score, f1_score,  jaccard_score, roc_auc_score, precision_score, recall_score
print('accuracy', accuracy_score(xpred, y_train1))



print('f1_score', f1_score(xpred, y_train1))



print('jaccard_score', jaccard_score(xpred, y_train1))
print('roc_auc_score', roc_auc_score(xpred, y_train1))
print('precision_score', precision_score(xpred, y_train1))

print('recall_score', recall_score(xpred, y_train1))


accuracy 0.9593253332991817
f1_score 0.9758122248792895
jaccard_score 0.9527669130441249
roc_auc_score 0.9343156984228156
precision_score 0.9811624167240983
recall_score 0.9705200648376786
